//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodrejMaterialDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDA_ManualStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IDA_ManualStructure()
        {
            this.IDA_GridData = new HashSet<IDA_GridData>();
            this.IDA_SubManualStructure = new HashSet<IDA_SubManualStructure>();
            this.IDA_SvgFiles = new HashSet<IDA_SvgFiles>();
        }
    
        public int ManualStructueId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string StructureName { get; set; }
        public string SerialNo { get; set; }
        public string ChasisNo { get; set; }
        public string ProjectNo { get; set; }
        public string CustomerCode { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDA_GridData> IDA_GridData { get; set; }
        public virtual IDA_Models IDA_Models { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDA_SubManualStructure> IDA_SubManualStructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDA_SvgFiles> IDA_SvgFiles { get; set; }
    }
}
