//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodrejMaterialDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDA_MasterGenericBOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IDA_MasterGenericBOM()
        {
            this.IDA_GenericBOM = new HashSet<IDA_GenericBOM>();
        }
    
        public int MasterGenericBomID { get; set; }
        public string ModelName { get; set; }
        public string Chapter { get; set; }
        public string SubChapter { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDA_GenericBOM> IDA_GenericBOM { get; set; }
    }
}
