//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodrejMaterialDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDA_Models
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IDA_Models()
        {
            this.IDA_ManualStructure = new HashSet<IDA_ManualStructure>();
        }
    
        public int ModelId { get; set; }
        public Nullable<System.Guid> MembershipUserId { get; set; }
        public string ModelName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDA_ManualStructure> IDA_ManualStructure { get; set; }
    }
}
